@startuml login_activity

|User|
start
:Open Application;

|System|
:Display Login Screen;

repeat
  |User|
  :Enter Email and Password;
  :Click "Login";

  |System|
  :Validate Credentials;

  backward:Display "Invalid Credentials" Message;
  repeat while (Valid Credentials?) is (no)
  ->yes;

  |User|
  :Provide User Role;

  |System|
  switch(User Role?)
  case (Admin)
    :Redirect to Admin Dashboard;
  case (Flight Agent)
    :Redirect to Flight Agent Dashboard;
  case (Customer)
    :Redirect to Customer Dashboard;
  endswitch

|User|
:View Dashboard;
stop

@enduml
